[setup]
python3 = true
postgresql = true
gcc = true

[install]
command = "python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[start]
command = "python manage.py runserver"

