[phases.setup]
apt_pkgs = ["python3", "postgresql", "gcc"]

[phases.install]
cmd = "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[phases.prestart]
cmd = ". /opt/venv/bin/activate && python manage.py migrate"

[phases.start]
cmd = ". /opt/venv/bin/activate && python manage.py runserver 0.0.0.0:8000"
